// This is a placeholder for types that would typically be generated by Supabase
// or defined more comprehensively.

export interface Profile {
  id: string; // UUID, matches auth.users.id
  user_type: 'supplier' | 'government_entity';
  full_name?: string | null;
  email?: string | null;
  service_category_id?: string | null; // UUID
  service_category?: { // Joined data from service_categories table
    id: string;
    name: string;
  } | null;
  registration_number?: string | null;
  location?: string | null;
  supplier_status?: 'active' | 'suspended' | 'blacklisted' | null;
  entity_name?: string | null;
  created_at: string; // TIMESTAMPTZ
  updated_at: string; // TIMESTAMPTZ
}

export interface ServiceCategory {
  id: string; // UUID
  name: string;
  created_at: string; // TIMESTAMPTZ
}

export interface Tender {
  id: string; // UUID
  title: string;
  reference_number: string;
  description?: string | null;
  issuing_entity_profile_id: string; // UUID, FK to profiles.id
  service_category_id: string; // UUID, FK to service_categories.id
  value?: number | null; // NUMERIC
  closing_date: string; // TIMESTAMPTZ
  status: 'open' | 'under_review' | 'awarded' | 'completed' | 'cancelled';
  created_at: string; // TIMESTAMPTZ
  updated_at: string; // TIMESTAMPTZ
}
