
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awvwjasafqpobjtwvwfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3dndqYXNhZnFwb2JqdHd2d2ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDI4NDUsImV4cCI6MjA2MjYxODg0NX0.MTh9QEYMMW2ph1lM1H5EeEaqLr5b2gacFhEIL7VT1uA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage, // Use local storage for session persistence
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true, // Important for OAuth and magic links, good to have
  },
});
